client side file
madzmadon/software-engineering-project-uno pull request #8
Opened 2024-04-08 01:57 UTC by Mberenice

worked

2024-04-08 01:59 UTC, madzmadon requested changes

2024-04-08 01:59 UTC, madzmadon commented on UNO/ClientCommunication/Client.java
> +<<<<<<< Updated upstream
Remove upstream comments

2024-04-08 16:31 UTC, madzmadon requested changes
Could  you add comments to describe what is happening in different pieces of the code?

2024-04-08 21:34 UTC, LPitt1 reviewed
Possible changes:
- The controllers are used as event handlers. Sending them through the client/server connection seems to undermine this purpose. To solve this, we could use the LoginData and CreateAccountData classes; however, they would need to be made serialized.
- Passing the UI elements instead of just their strings would help if the controller classes needed more control over the UI.
- The client class needs to be extended from the abstract client class from OCSF and; therefore, the required method would need to be overridden.

2024-04-11 15:26 UTC, madzmadon requested changes

2024-04-11 15:26 UTC, madzmadon commented on UNO/ClientCommunication/GameSessionControl.java
**Recommended to add**

 Fields
    - game session data
    - List of players in the game
    - Index of the current player
 public void addPlayer(ClientHandler player) 

 public void removePlayer(ClientHandler player) 
    
public ClientHandler getCurrentPlayer() 

public void nextTurn() 

public boolean isValidMove(Card card) 
 -Check if the played card is a valid move based on the game rules
 -Example: Check if the card matches the color or value of the top card in the discard pile

public void playCard(ClientHandler player, Card card) 
 - Remove the card from the player's hand
 - Add the card to the discard pile
 -if card type equals "Draw Two, Draw Four", next player draws cards
-Add more conditions for other special card effects

public Card drawCard() 

public void callUno(ClientHandler player) 
- Handle the player calling UNO
-Example: Check if the player has only one card left and apply any penalties if they didn't call UNO in time

public boolean isGameOver() 
-Check if the game is over
-Example: Check if any player has an empty hand

public void broadcastMessage(String message) 
-send players valid messages from server for when they play a bad card, the server will send you this message, you just have to display it

public GameSessionData getGameSessionData() 

private ClientHandler getNextPlayer()

2024-04-11 15:37 UTC, madzmadon requested changes

2024-04-11 15:37 UTC, madzmadon commented on UNO/ClientCommunication/GameControl.java
>  }
// add gameId to Fields
private int gameId;

add this.gameId = gameId; to constructor

// Method to get the game ID
public int getGameId() {... }

2024-04-13 14:40 UTC, merged